// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/block/getBlock": {
            "get": {
                "description": "查询区块",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "区块查询"
                ],
                "summary": "查询区块",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/block.GetBlockReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/block.GetBlockRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/block.ErrRes"
                        }
                    }
                }
            }
        },
        "/block/getTransaction": {
            "get": {
                "description": "查询交易",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "区块查询"
                ],
                "summary": "查询交易",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/block.GetTxReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/block.GetTxRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/block.ErrRes"
                        }
                    }
                }
            }
        },
        "/block/getTransactionLogs": {
            "get": {
                "description": "查询收据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "区块查询"
                ],
                "summary": "查询收据",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/block.GetTxReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/block.GetReceiptsRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/block.ErrRes"
                        }
                    }
                }
            }
        },
        "/block/viewBlocks": {
            "get": {
                "description": "查询区块列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "区块查询"
                ],
                "summary": "查询区块列表",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/block.PageReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/block.ViewBlocksRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/block.ErrRes"
                        }
                    }
                }
            }
        },
        "/block/viewTransactions": {
            "get": {
                "description": "查询交易列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "区块查询"
                ],
                "summary": "查询交易列表",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/block.TxPageReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/block.ViewTxsRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/block.ErrRes"
                        }
                    }
                }
            }
        },
        "/exchanger": {
            "get": {
                "description": "按地址查询交易所",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "交易所"
                ],
                "summary": "查询交易所",
                "parameters": [
                    {
                        "type": "string",
                        "description": "交易所地址",
                        "name": "address",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/exchanger.ExchangerRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/exchanger.ExchangerRes"
                        }
                    }
                }
            }
        },
        "/exchanger/page": {
            "get": {
                "description": "按创建时间逆序查询交易所列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "交易所"
                ],
                "summary": "查询交易所列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "页，默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "页大小，默认10",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/exchanger.PageRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/exchanger.PageRes"
                        }
                    }
                }
            }
        },
        "/extra/checkAuth": {
            "get": {
                "description": "查询交易所状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "其他接口"
                ],
                "summary": "查询交易所状态",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/extra.CheckAuthReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/extra.CheckAuthRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/extra.ErrRes"
                        }
                    }
                }
            }
        },
        "/extra/requestErbTest": {
            "get": {
                "description": "请求ERB测试币",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "其他接口"
                ],
                "summary": "请求ERB测试币",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/extra.RequestErbTestReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/extra.RequestErbTestRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/extra.ErrRes"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "NFT.ErrRes": {
            "type": "object",
            "properties": {
                "err": {
                    "description": "错误信息",
                    "type": "string"
                }
            }
        },
        "NFT.GetBlockReq": {
            "type": "object",
            "properties": {
                "block_number": {
                    "description": "区块号",
                    "type": "string"
                }
            }
        },
        "NFT.GetBlockRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/database.Block"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "NFT.GetReceiptsRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.TxLog"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "NFT.GetTxReq": {
            "type": "object",
            "properties": {
                "tx_hash": {
                    "description": "交易hash",
                    "type": "string"
                }
            }
        },
        "NFT.GetTxRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/database.Transaction"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "NFT.PageReq": {
            "type": "object",
            "properties": {
                "page": {
                    "description": "页",
                    "type": "integer"
                },
                "page_size": {
                    "description": "页码",
                    "type": "integer"
                }
            }
        },
        "NFT.TxPageReq": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "地址 不区分传 \"\"",
                    "type": "string"
                },
                "block_number": {
                    "description": "区块号 不区分",
                    "type": "string"
                },
                "page": {
                    "description": "页",
                    "type": "integer"
                },
                "page_size": {
                    "description": "页码",
                    "type": "integer"
                },
                "tx_type": {
                    "description": "交易类型  如ERC20  ERC1155 ERC721  internal  不区分传\"\"",
                    "type": "string"
                }
            }
        },
        "NFT.ViewBlocksRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Block"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "NFT.ViewTxsRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Transaction"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "block.ErrRes": {
            "type": "object",
            "properties": {
                "err": {
                    "description": "错误信息",
                    "type": "string"
                }
            }
        },
        "block.GetBlockReq": {
            "type": "object",
            "properties": {
                "block_number": {
                    "description": "区块号",
                    "type": "string"
                }
            }
        },
        "block.GetBlockRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/database.Block"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "block.GetReceiptsRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.TxLog"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "block.GetTxReq": {
            "type": "object",
            "properties": {
                "tx_hash": {
                    "description": "交易hash",
                    "type": "string"
                }
            }
        },
        "block.GetTxRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/database.Transaction"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "block.PageReq": {
            "type": "object",
            "properties": {
                "page": {
                    "description": "页",
                    "type": "integer"
                },
                "page_size": {
                    "description": "页码",
                    "type": "integer"
                }
            }
        },
        "block.TxPageReq": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "地址 不区分传 \"\"",
                    "type": "string"
                },
                "block_number": {
                    "description": "区块号 不区分",
                    "type": "string"
                },
                "page": {
                    "description": "页",
                    "type": "integer"
                },
                "page_size": {
                    "description": "页码",
                    "type": "integer"
                },
                "tx_type": {
                    "description": "交易类型  如ERC20  ERC1155 ERC721  internal  不区分传\"\"",
                    "type": "string"
                }
            }
        },
        "block.ViewBlocksRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Block"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "block.ViewTxsRes": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Transaction"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "database.Block": {
            "type": "object",
            "properties": {
                "difficulty": {
                    "type": "string"
                },
                "extraData": {
                    "type": "string"
                },
                "gasLimit": {
                    "type": "string"
                },
                "gasUsed": {
                    "type": "string"
                },
                "miner": {
                    "type": "string"
                },
                "mixHash": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "parentHash": {
                    "type": "string"
                },
                "receiptsRoot": {
                    "type": "string"
                },
                "sha3Uncles": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                },
                "stateRoot": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "transactionsRoot": {
                    "type": "string"
                },
                "tx_count": {
                    "type": "integer"
                }
            }
        },
        "database.Exchanger": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "交易所地址",
                    "type": "string"
                },
                "block_number": {
                    "description": "创建时的区块号",
                    "type": "integer"
                },
                "creator": {
                    "description": "创建者地址",
                    "type": "string"
                },
                "fee_ratio": {
                    "description": "手续费率,单位万分之一",
                    "type": "integer"
                },
                "is_open": {
                    "description": "是否开启中",
                    "type": "boolean"
                },
                "name": {
                    "description": "交易所名称",
                    "type": "string"
                },
                "timestamp": {
                    "description": "开启时间",
                    "type": "integer"
                },
                "tx_hash": {
                    "description": "创建的交易",
                    "type": "string"
                },
                "url": {
                    "description": "交易所URL",
                    "type": "string"
                }
            }
        },
        "database.Transaction": {
            "type": "object",
            "properties": {
                "blockHash": {
                    "type": "string"
                },
                "blockNumber": {
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "gas": {
                    "type": "string"
                },
                "gasPrice": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "input": {
                    "type": "string"
                },
                "internal_calls": {
                    "type": "string"
                },
                "internal_value_transfer": {
                    "type": "string"
                },
                "nonce": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "token_transfer": {
                    "type": "string"
                },
                "transactionIndex": {
                    "type": "string"
                },
                "tx_type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "database.TxLog": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "topics": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                }
            }
        },
        "exchanger.ExchangerRes": {
            "type": "object",
            "properties": {
                "err_str": {
                    "description": "查询错误字符串，如果有",
                    "type": "string"
                },
                "exchangers": {
                    "description": "交易所",
                    "$ref": "#/definitions/database.Exchanger"
                }
            }
        },
        "exchanger.PageRes": {
            "type": "object",
            "properties": {
                "err_str": {
                    "description": "查询错误字符串，如果有",
                    "type": "string"
                },
                "exchangers": {
                    "description": "交易所列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.Exchanger"
                    }
                },
                "total": {
                    "description": "交易所总数",
                    "type": "integer"
                }
            }
        },
        "extra.CheckAuthReq": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "地址",
                    "type": "string"
                }
            }
        },
        "extra.CheckAuthRes": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "0 成功  1 地址有误 其他失败",
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/extra.CheckAuthResData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "extra.CheckAuthResData": {
            "type": "object",
            "properties": {
                "exchanger_balance": {
                    "type": "string"
                },
                "exchanger_flag": {
                    "type": "boolean"
                },
                "status": {
                    "description": "2 交易所付费状态正常  其他数字为欠费或者没交费",
                    "type": "integer"
                }
            }
        },
        "extra.ErrRes": {
            "type": "object",
            "properties": {
                "err": {
                    "description": "错误信息",
                    "type": "string"
                }
            }
        },
        "extra.RequestErbTestReq": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "地址",
                    "type": "string"
                }
            }
        },
        "extra.RequestErbTestRes": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "0 成功  1 地址有误 其他失败",
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "127.0.0.1:3001",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Gin swagger",
	Description: "区块链监控程序后端",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
