definitions:
  NFT.ErrRes:
    properties:
      err_str:
        description: 错误字符串
        type: string
    type: object
  NFT.PageRes:
    properties:
      nfts:
        description: NFT列表
        items:
          $ref: '#/definitions/database.UserNFT'
        type: array
      total:
        description: NFT总数
        type: integer
    type: object
  NFT.PageTxRes:
    properties:
      nft_txs:
        description: NFT交易列表
        items:
          $ref: '#/definitions/database.NFTTx'
        type: array
      total:
        description: NFT总数
        type: integer
    type: object
  SNFT.ErrRes:
    properties:
      err_str:
        description: 错误字符串
        type: string
    type: object
  SNFT.PageRes:
    properties:
      nfts:
        description: SNFT列表
        items:
          $ref: '#/definitions/database.SNFT'
        type: array
      total:
        description: SNFT总数
        type: integer
    type: object
  block.ErrRes:
    properties:
      err:
        description: 错误信息
        type: string
    type: object
  block.GetBlockReq:
    properties:
      block_number:
        description: 区块号
        type: string
    type: object
  block.GetBlockRes:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/database.Block'
      msg:
        type: string
    type: object
  block.GetReceiptsRes:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/database.TxLog'
        type: array
      msg:
        type: string
    type: object
  block.GetTxReq:
    properties:
      tx_hash:
        description: 交易hash
        type: string
    type: object
  block.GetTxRes:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/database.Transaction'
      msg:
        type: string
    type: object
  block.PageReq:
    properties:
      page:
        description: 页
        type: integer
      page_size:
        description: 页码
        type: integer
    type: object
  block.TxPageReq:
    properties:
      address:
        description: 地址 不区分传 ""
        type: string
      block_number:
        description: 区块号 不区分
        type: string
      page:
        description: 页
        type: integer
      page_size:
        description: 页码
        type: integer
      tx_type:
        description: 交易类型  如ERC20  ERC1155 ERC721  internal  不区分传""
        type: string
    type: object
  block.ViewBlocksRes:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/database.Block'
        type: array
      msg:
        type: string
      total:
        type: integer
    type: object
  block.ViewTxsRes:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/database.Transaction'
        type: array
      msg:
        type: string
      total:
        type: integer
    type: object
  database.Block:
    properties:
      difficulty:
        type: string
      extraData:
        type: string
      gasLimit:
        type: string
      gasUsed:
        type: string
      miner:
        type: string
      mixHash:
        type: string
      number:
        type: string
      parentHash:
        type: string
      receiptsRoot:
        type: string
      sha3Uncles:
        type: string
      size:
        type: string
      stateRoot:
        type: string
      timestamp:
        type: string
      transactionsRoot:
        type: string
      tx_count:
        type: integer
    type: object
  database.Exchanger:
    properties:
      address:
        description: 交易所地址
        type: string
      block_number:
        description: 创建时的区块号
        type: integer
      creator:
        description: 创建者地址
        type: string
      fee_ratio:
        description: 手续费率,单位万分之一
        type: integer
      is_open:
        description: 是否开启中
        type: boolean
      name:
        description: 交易所名称
        type: string
      nft_count:
        description: NFT总数，批量查询的此字段无效
        type: integer
      timestamp:
        description: 开启时间
        type: integer
      tx_hash:
        description: 创建的交易
        type: string
      url:
        description: 交易所URL
        type: string
    type: object
  database.NFTTx:
    properties:
      exchanger_addr:
        description: 交易所地址
        type: string
      from:
        description: 卖家
        type: string
      nft_addr:
        description: 交易的NFT地址
        type: string
      price:
        description: 价格,单位为wei
        type: string
      timestamp:
        description: 交易时间戳
        type: integer
      to:
        description: 买家
        type: string
      tx_hash:
        description: 交易哈希
        type: string
      tx_type:
        description: 交易类型,1：转移、2:出价成交、3:定价购买、4：惰性定价购买、5：惰性定价购买、6：出价成交、7：惰性出价成交、8：撮合交易
        type: integer
    type: object
  database.SNFT:
    properties:
      address:
        description: SNFT地址
        type: string
      awardee:
        description: 被奖励的矿工获地址
        type: string
      create_at:
        description: 创建时间戳
        type: integer
      create_number:
        description: 创建的区块高度
        type: integer
      creator:
        description: 创建者地址
        type: string
      meta_url:
        description: 元信息链接
        type: string
      owner:
        description: 所有者,未分配和回收的为null
        type: string
      reward_at:
        description: 奖励时间戳,矿工被奖励这个SNFT的时间
        type: integer
      reward_number:
        description: 奖励区块高度,矿工被奖励这个SNFT的区块高度
        type: integer
      royalty_ratio:
        description: 版税费率,单位万分之一
        type: integer
    type: object
  database.Transaction:
    properties:
      blockHash:
        type: string
      blockNumber:
        type: string
      from:
        type: string
      gas:
        type: string
      gasPrice:
        type: string
      hash:
        type: string
      input:
        type: string
      internal_calls:
        type: string
      internal_value_transfer:
        type: string
      nonce:
        type: string
      status:
        type: string
      timestamp:
        type: string
      to:
        type: string
      token_transfer:
        type: string
      transactionIndex:
        type: string
      tx_type:
        type: string
      value:
        type: string
    type: object
  database.TxLog:
    properties:
      address:
        type: string
      data:
        type: string
      topics:
        type: string
      tx_hash:
        type: string
    type: object
  database.UserNFT:
    properties:
      address:
        description: NFT地址
        type: string
      block_number:
        description: 创建的区块高度
        type: integer
      creator:
        description: 创建者地址
        type: string
      exchanger_addr:
        description: 所在交易所地址,没有的可以在任意交易所交易
        type: string
      meta_url:
        description: 元信息URL
        type: string
      owner:
        description: 所有者
        type: string
      royalty_ratio:
        description: 版税费率,单位万分之一
        type: integer
      timestamp:
        description: 创建时间戳
        type: integer
      tx_hash:
        description: 创建的交易哈希
        type: string
    type: object
  exchanger.ErrRes:
    properties:
      err_str:
        description: 错误字符串
        type: string
    type: object
  exchanger.PageRes:
    properties:
      exchangers:
        description: 交易所列表
        items:
          $ref: '#/definitions/database.Exchanger'
        type: array
      total:
        description: 交易所总数
        type: integer
      yesterday_total:
        description: 昨日新开交易所数量
        type: integer
    type: object
  extra.CheckAuthReq:
    properties:
      address:
        description: 地址
        type: string
    type: object
  extra.CheckAuthRes:
    properties:
      code:
        description: 0 成功  1 地址有误 其他失败
        type: integer
      data:
        $ref: '#/definitions/extra.CheckAuthResData'
      msg:
        type: string
    type: object
  extra.CheckAuthResData:
    properties:
      exchanger_balance:
        type: string
      exchanger_flag:
        type: boolean
      status:
        description: 2 交易所付费状态正常  其他数字为欠费或者没交费
        type: integer
    type: object
  extra.ErrRes:
    properties:
      err:
        description: 错误信息
        type: string
    type: object
  extra.RequestErbTestReq:
    properties:
      address:
        description: 地址
        type: string
    type: object
  extra.RequestErbTestRes:
    properties:
      code:
        description: 0 成功  1 地址有误 其他失败
        type: integer
      msg:
        type: string
    type: object
info:
  contact: {}
  description: 区块链监控程序后端
  title: Gin swagger
  version: "1.0"
paths:
  /block/getBlock:
    get:
      consumes:
      - application/json
      description: 查询区块
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/block.GetBlockReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/block.GetBlockRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/block.ErrRes'
      summary: 查询区块
      tags:
      - 区块查询
  /block/getTransaction:
    get:
      consumes:
      - application/json
      description: 查询交易
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/block.GetTxReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/block.GetTxRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/block.ErrRes'
      summary: 查询交易
      tags:
      - 区块查询
  /block/getTransactionLogs:
    get:
      consumes:
      - application/json
      description: 查询收据
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/block.GetTxReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/block.GetReceiptsRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/block.ErrRes'
      summary: 查询收据
      tags:
      - 区块查询
  /block/viewBlocks:
    get:
      consumes:
      - application/json
      description: 查询区块列表
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/block.PageReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/block.ViewBlocksRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/block.ErrRes'
      summary: 查询区块列表
      tags:
      - 区块查询
  /block/viewTransactions:
    get:
      consumes:
      - application/json
      description: 查询交易列表
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/block.TxPageReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/block.ViewTxsRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/block.ErrRes'
      summary: 查询交易列表
      tags:
      - 区块查询
  /exchanger/get:
    get:
      consumes:
      - application/json
      description: 按地址查询交易所
      parameters:
      - description: 交易所地址
        in: query
        name: addr
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.Exchanger'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exchanger.ErrRes'
      summary: 查询交易所
      tags:
      - 交易所
  /exchanger/page:
    get:
      consumes:
      - application/json
      description: 按创建时间逆序查询交易所列表
      parameters:
      - description: 交易所名称,空则查询所有交易所
        in: query
        name: name
        type: string
      - description: 页,默认1
        in: query
        name: page
        type: string
      - description: 页大小,默认10
        in: query
        name: page_size
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/exchanger.PageRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exchanger.ErrRes'
      summary: 查询交易所列表
      tags:
      - 交易所
  /extra/checkAuth:
    get:
      consumes:
      - application/json
      description: 查询交易所状态
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/extra.CheckAuthReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/extra.CheckAuthRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/extra.ErrRes'
      summary: 查询交易所状态
      tags:
      - 其他接口
  /extra/requestErbTest:
    get:
      consumes:
      - application/json
      description: 请求ERB测试币
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/extra.RequestErbTestReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/extra.RequestErbTestRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/extra.ErrRes'
      summary: 请求ERB测试币
      tags:
      - 其他接口
  /nft/page:
    get:
      consumes:
      - application/json
      description: 按创建时间逆序查询NFT列表
      parameters:
      - description: 交易所，空则查询所有交易所
        in: query
        name: exchanger
        type: string
      - description: 所有者,空则查询所有
        in: query
        name: owner
        type: string
      - description: 页,默认1
        in: query
        name: page
        type: string
      - description: 页大小,默认10
        in: query
        name: page_size
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/NFT.PageRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/NFT.ErrRes'
      summary: 查询NFT列表
      tags:
      - NFT
  /nft/tx/page:
    get:
      consumes:
      - application/json
      description: 按创建时间逆序查询NFT交易列表
      parameters:
      - description: 交易所，空则查询所有交易所
        in: query
        name: exchanger
        type: string
      - description: 指定帐户,空则查询所有帐户的
        in: query
        name: account
        type: string
      - description: 页,默认1
        in: query
        name: page
        type: string
      - description: 页大小,默认10
        in: query
        name: page_size
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/NFT.PageTxRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/NFT.ErrRes'
      summary: 查询NFT交易列表
      tags:
      - NFT
  /snft/block:
    get:
      consumes:
      - application/json
      description: 查询指定区块的SNFT奖励列表
      parameters:
      - description: 区块号
        in: query
        name: number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.SNFT'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/SNFT.ErrRes'
      summary: 查询区块SNFT列表
      tags:
      - SNFT
  /snft/page:
    get:
      consumes:
      - application/json
      description: 按创建时间逆序查询SNFT列表
      parameters:
      - description: 所有者,空则查询所有
        in: query
        name: owner
        type: string
      - description: 页,默认1
        in: query
        name: page
        type: string
      - description: 页大小,默认10
        in: query
        name: page_size
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/SNFT.PageRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/SNFT.ErrRes'
      summary: 查询SNFT列表
      tags:
      - SNFT
swagger: "2.0"
